name: HEU Bug Report Template
description: To report any HEU related bug
title: "[Bug]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of bug would you like to report?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Correctness/Accuracy
        - Others
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: HEU Version
      description: pip version if installed from package, commit id if build
        from source
      placeholder: e.g., sf-heu 0.5.0b0
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS Platform and Distribution
      placeholder: e.g., Linux Ubuntu 22.04
    validations:
      required: true
  - type: input
    id: Python
    attributes:
      label: Python Version
      placeholder: e.g., 3.9
    validations:
      required: true
  - type: input
    id: Compiler
    attributes:
      label: Compiler Version
      description: if compiling from source
      placeholder: e.g., GCC 11.2.1
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Current Behavior?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: code-to-reproduce
    attributes:
      label: Standalone code to reproduce the issue
      description: Provide a reproducible test case that is the bare minimum
        necessary to generate the problem. If possible, please share a link to
        Jupyter/any notebook.
      placeholder: Tell us what you see!
      value: print("A bug")
      render: Python
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: Shell
