name: HEU Feature Request Template
description: To request a new feature
title: "[Feature]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Feature Request Type
      description: What kind of feature would you like to request?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Usability
        - Documentation
        - HE Algorithms
        - Language binding
        - Others
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the context
      value: A clear and concise description of the context in which the feature will be used.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      value: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      value: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      value: Add any other context or screenshots about the feature request here.
    validations:
      required: false
