# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('../bazel-bin/heu/pybind'))

# -- Project information -----------------------------------------------------

project = 'HEU'
copyright = '2022 Ant Group Co., Ltd'
author = 'HEU authors'

# The full version, including alpha/beta/rc tags
# release = '0.0.6'

# -- Multi-language config ---------------------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

locale_dirs = ['locale/']  # path is example but recommended.
gettext_compact = False  # optional.
gettext_uuid = False  # optional.

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    "sphinx_inline_tabs",
    # "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

html_favicon = '_static/favicon.ico'

html_css_files = [
    'css/custom.css',
]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

html_context = {
    "default_mode": "light"
}

html_sidebars = {
    "**": ["search-field", "sidebar-nav-bs"]
}

html_theme_options = {
    "logo": {
        "text": "HEU",
        "image_light": "logo.png",
        "image_dark": "logo-dark.png",
    },
    "pygment_light_style": "tango",
    "pygment_dark_style": "native",
    "external_links": [
        {"name": "SecretFlow", "url": "https://secretflow.readthedocs.io/"},
        {"name": "SPU", "url": "https://spu.readthedocs.io/"},
    ],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/secretflow/heu",
            "icon": "fab fa-github",
            "type": "fontawesome",
        },
    ],
    "footer_items": ["copyright"],
    "page_sidebar_items": ["page-toc"],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
